# Generated by Django 5.0.1 on 2024-02-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank="True", max_length=50, null="True"),
                ),
                ("category_img", models.ImageField(upload_to="category/")),
            ],
        ),
        migrations.CreateModel(
            name="Staffregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("age", models.IntegerField(default=0)),
                ("contact_no", models.IntegerField(default=0)),
                ("email", models.EmailField(blank="True", max_length=100, null="True")),
                (
                    "password",
                    models.CharField(blank="True", max_length=255, null="True"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prod_name",
                    models.CharField(blank="True", max_length=50, null="True"),
                ),
                ("prod_price", models.IntegerField(null="True")),
                ("prod_image", models.ImageField(upload_to="product/")),
                ("prod_discription", models.TextField(null="True")),
                (
                    "prod_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archi.category"
                    ),
                ),
            ],
        ),
    ]
