# Generated by Django 5.0.1 on 2024-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_resgistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("age", models.IntegerField(default=0)),
                ("contact_no", models.IntegerField(default=0)),
                ("email", models.EmailField(blank="True", max_length=100, null="True")),
                (
                    "password",
                    models.CharField(blank="True", max_length=255, null="True"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Staffregistration",
        ),
    ]
